name: DEPLOY STAGING

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Version Theme
        run: npm run update-version
     # - name: Delete Ignored Folder
      #  run: npm run remove-ignored-folders
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: 35.245.151.137
          # ftp username
          username: ${{ secrets.SERVER_USER }}
          # ftp password
          password: ${{ secrets.SERVER_PASSWORD }}
          # Server port to connect to (read your web hosts docs)
          port: 50647
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp
          # Folder to upload from, must end with trailing slash /
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /www/${{secrets.SERVER_USER}}_933/public/wp-content/themes/nicole-hunn-members/
        env:
          ARGS: --delete
